version: '3'

services:
  mysql:
    container_name: duckguess-mysql
    image: mysql
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - duckguess-network

  backend:
    container_name: duckguess-api
    build:
      context: ./duckguess-api
      dockerfile: Dockerfile
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQL_HOST
      - DB_USER=$MYSQL_USER
      - DB_DATABASE=$MYSQL_DATABASE
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - DB_PORT=$MYSQL_DOCKER_PORT
      - API_PORT=$API_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    volumes:
      - ./duckguess-api:/usr/app
    depends_on:
      - mysql
    networks:
      - duckguess-network

  frontend:
    container_name: duckguess-ui
    build:
      context: ./duckguess-ui
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $UI_LOCAL_PORT:$UI_DOCKER_PORT
    volumes:
      - ./duckguess-ui:/usr/app
    depends_on:
      - backend
    networks:
      - duckguess-network

networks:
  duckguess-network:
    driver: bridge